### ISSUE TITLE
AGREE generates error message for large array

### ISSUE THREAD

**Issue by cong-liu-2000** [loonwerks/AGREE#52]
AGREE generates unknow error message for Phase 2 model.
The error seems to be triggered by the large array used in the following contract:
		annex agree {**
			guarantee Req_Filter_LST "Well-formed Line Search Task message" :
			if event(filter_in) and CASEAgree::WELL_FORMED_LINE_SEARCH_TASK(filter_in) then
			   event(filter_out) and (filter_out = filter_in)
			else not(event(filter_out));
		**};

    fun WELL_FORMED_LINE_SEARCH_TASK(msg : CMASI::LineSearchTask.i) : bool =
        msg.TaskID >= TASK_ID_MIN and msg.TaskID <= TASK_ID_MAX and
        (forall point in msg.PointList, WELL_FORMED_POINT(point)) and
        (forall viewangle in msg.ViewAngleList, WELL_FORMED_VIEWANGLE(viewangle));

    data implementation LineSearchTask.i extends SearchTask.i
    	subcomponents
    		-- Line to search
    		-- PointList: data Location3D.i {Data_Model::Data_Representation => Array; Data_Model::Dimension => (1024);};
    		PointList: data PointListArray;
    		
    		-- Defines a list of acceptable look-angles for this task.  See the documentation above for details. --
    		-- ViewAngleList: data Wedge.i {Data_Model::Data_Representation => Array; Data_Model::Dimension => (16);};
    		ViewAngleList: data WedgeArray;
    		
    		UseInertialViewAngles: data Boolean;
		properties
			HAMR::Bit_Codec_Max_Size => CM_Property_Set::LineSearchTask_Bit_Codec_Max_Size;
    end LineSearchTask.i;

    data PointListArray
			properties
				Data_Model::Data_Representation => Array;
				Data_Model::Base_Type => (classifier (Location3D.i));
				Data_Model::Dimension => (1024);
    end PointListArray;

Run jkind on the generated Lustre file:
>jkind -solver z3 sw.lus
Warning at line 261:49 unguarded pre expression
Warning at line 283:224 unguarded pre expression
Warning at line 305:679 unguarded pre expression
Warning at line 327:37 unguarded pre expression
Warning at line 353:121 unguarded pre expression
Warning at line 379:112 unguarded pre expression
Warning at line 401:224 unguarded pre expression
Warning at line 423:214 unguarded pre expression
Warning at line 445:57293 unguarded pre expression
==========================================
  JKind 4.4.1
==========================================

There are 6 properties to be checked.
PROPERTIES TO BE CHECKED: [FC_UART____ASSUME0, FC_UART____ASSUME1, RADIO____ASSUME0, __ASSUME__HIST, __GUARANTEE0, __GUARANTEE1]

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
UNKNOWN PROPERTIES: [FC_UART____ASSUME0, FC_UART____ASSUME1, RADIO____ASSUME0, __ASSUME__HIST, __GUARANTEE0, __GUARANTEE1] || True for 0 steps || Time = 0.108s
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    -------------------------------------
    --^^--        SUMMARY          --^^--
    -------------------------------------

UNKNOWN PROPERTIES: [FC_UART____ASSUME0, FC_UART____ASSUME1, RADIO____ASSUME0, __ASSUME__HIST, __GUARANTEE0, __GUARANTEE1]

bmc process failed
java.lang.StackOverflowError
        at jkind.translation.Lustre2Sexp.visit(Lustre2Sexp.java:157)
        at jkind.translation.Lustre2Sexp.visit(Lustre2Sexp.java:40)
        at jkind.lustre.BinaryExpr.accept(BinaryExpr.java:27)
        at jkind.translation.Lustre2Sexp.visit(Lustre2Sexp.java:157)
        at jkind.translation.Lustre2Sexp.visit(Lustre2Sexp.java:40)
        at jkind.lustre.BinaryExpr.accept(BinaryExpr.java:27)

After reduce array size to 10, the error message is gone.
    data PointListArray
			properties
				Data_Model::Data_Representation => Array;
				Data_Model::Base_Type => (classifier (Location3D.i));
				Data_Model::Dimension => (10);
    end PointListArray;

**Comment by cong-liu-2000** [comment]
The SW Lustre file:
[sw.txt](https://github.com/loonwerks/AGREE/files/5859317/sw.txt)

**Comment by kfhoech** [comment]
This limitation is primarily due to the underlying JLustre input to JKind where there are no quantification operators.  Thus, array expressions must be flattened to conjunctions or disjunctions.  The limitation may be mitigated in introducing intermediate variables to reduce the expression size and balancing the expression trees, but this is only a mitigation, not a solution.

JKind needs to be enhanced before this can properly be solved.

Additionally, due to the multiplication of state space of the SMT problems generated, making analysis of large arrays tractable is going to require better support for theories over arrays in the SMT and support for using that in JKind.
