### ISSUE TITLE
AGREE fail to analyze the Integer Toy example with solver Z3

### ISSUE THREAD

**Issue by cong-liu-2000** [loonwerks/AGREE#76]
There is no issue if running AGREE with solver SMTInterpol.
There is no issue if running jkind in command line to analyze the translated Lustre model with solver z3.

**AGREE IDE console dump:**
 JKindException Text 
jkind.JKindException: Abnormal termination, exit code -8
Warning at line 183:43 unguarded pre expression
  JKind 4.4.1

There are 5 properties to be checked.
PROPERTIES TO BE CHECKED: [A_sub____ASSUME0, B_sub____ASSUME0, __ASSUME__HIST, __GUARANTEE0, __GUARANTEE1]

	at jkind.api.ApiUtil.callJKind(ApiUtil.java:108)
	at jkind.api.ApiUtil.execute(ApiUtil.java:47)
	at jkind.api.JKindApi.execute(JKindApi.java:173)
	at jkind.api.KindApi.execute(KindApi.java:77)
	at jkind.api.KindApi.execute(KindApi.java:59)
	at com.rockwellcollins.atc.agree.analysis.handlers.VerifyHandler$1.run(VerifyHandler.java:583)
Abnormal termination, exit code -8

**Comment by cong-liu-2000** [comment]
But why there is no issue if running jkind in command line to analyze the translated Lustre model with solver z3?

**Comment by cong-liu-2000** [comment]
The jkind version in command line is 4.4.1. Is this the reason?

**Comment by lgwagner** [comment]
Yes.
